/**
 * Handles administrator session management and XOR encryption simulation.
 */

const ENCRYPT_KEY = 0x5A; // Mirrors the XOR encryption key in auth.c

/**
 * Simulates byte-wise XOR encryption, returning a hex string suitable for localStorage.
 * @param {string} text 
 * @returns {string} Hex representation of XOR'd characters
 */
function encrypt(text) {
    let hexResult = '';
    for (let i = 0; i < text.length; i++) {
        const xorValue = text.charCodeAt(i) ^ ENCRYPT_KEY;
        hexResult += xorValue.toString(16).padStart(2, '0');
    }
    return hexResult;
}

/**
 * Decrypts a hex string generated by the encrypt function.
 * @param {string} hex 
 * @returns {string} Plaintext string
 */
function decrypt(hex) {
    let textResult = '';
    for (let i = 0; i < hex.length; i += 2) {
        const byteVal = parseInt(hex.substring(i, i + 2), 16);
        textResult += String.fromCharCode(byteVal ^ ENCRYPT_KEY);
    }
    return textResult;
}

/**
 * Initializes the administrative account in localStorage if not already present.
 */
export function initAdminAccount() {
    if (!localStorage.getItem('sms_admin_username')) {
        localStorage.setItem('sms_admin_username', 'admin');
        localStorage.setItem('sms_admin_password', encrypt('password123')); // default password
    }
}

/**
 * Authenticates credentials against the stored admin values.
 * @param {string} username 
 * @param {string} password 
 * @returns {boolean}
 */
export function authenticateAdmin(username, password) {
    initAdminAccount();
    const storedUser = localStorage.getItem('sms_admin_username');
    const storedPassHex = localStorage.getItem('sms_admin_password');
    
    if (!storedUser || !storedPassHex) return false;
    
    const decryptedPass = decrypt(storedPassHex);
    return username === storedUser && password === decryptedPass;
}

/**
 * Updates the administrator password.
 * @param {string} oldPass 
 * @param {string} newPass 
 * @returns {boolean} True if password was successfully updated, false otherwise.
 */
export function changeAdminPassword(oldPass, newPass) {
    initAdminAccount();
    const storedPassHex = localStorage.getItem('sms_admin_password');
    const decryptedPass = decrypt(storedPassHex);
    
    if (oldPass !== decryptedPass) {
        return false;
    }
    
    localStorage.setItem('sms_admin_password', encrypt(newPass));
    return true;
}
